import { Ad, Competitor, UserPlan } from '@/types/frontend';

export const mockUserPlan: UserPlan = {
  name: 'starter',
  adsLimit: 200,
  adsUsed: 156,
  analysisLimit: 50,
  analysisUsed: 34,
  competitorLimit: 3,
  competitorUsed: 3,
};

export const mockCompetitors: Competitor[] = [
  {
    id: '1',
    name: 'Concorrente Alpha',
    metaPageId: 'alpha_ads_page',
    googleDomain: 'alpha.com.br',
    adCount: 142,
    newAdsLast7Days: 28,
    averageScore: 7.2,
    lastScan: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: '2',
    name: 'Beta Store',
    metaPageId: 'betastore_oficial',
    adCount: 67,
    newAdsLast7Days: 5,
    averageScore: 6.8,
    lastScan: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: '3',
    name: 'Gama Fashion',
    googleDomain: 'gama.com',
    adCount: 89,
    newAdsLast7Days: 12,
    averageScore: 8.1,
    lastScan: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
];

export const mockAds: Ad[] = [
  {
    id: 'ad1',
    externalId: 'ext_1',
    platform: 'meta',
    competitorId: '1',
    competitorName: 'Concorrente Alpha',
    thumbnailUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=400&h=500',
    headline: 'Oferta Exclusiva de Verão: 40% OFF',
    text: 'Aproveite nossa coleção de verão com descontos imperdíveis. Estoque limitado!',
    ctaText: 'Comprar Agora',
    landingPageUrl: 'https://alpha.com.br/verao',
    status: 'active',
    startDate: '2026-02-14',
    daysActive: 45,
    score: 8,
    isWinner: true,
    isNew: false,
    analysis: {
      hook: 'Usa uma oferta direta de 40% OFF para atrair atenção imediata.',
      offer: 'Desconto agressivo em toda a coleção de verão.',
      cta: 'Direto e focado em conversão imediata.',
      tone: 'Urgente e promocional.',
      targetAudience: 'Pessoas interessadas em moda praia e descontos.',
      strengths: ['Oferta clara', 'Visual atraente'],
      weaknesses: ['Texto curto demais'],
      suggestions: ['Adicionar prova social'],
    },
  },
  {
    id: 'ad2',
    externalId: 'ext_2',
    platform: 'google',
    competitorId: '3',
    competitorName: 'Gama Fashion',
    thumbnailUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=400&h=500',
    headline: 'O segredo para um look impecável',
    text: 'Descubra como combinar nossas peças exclusivas para qualquer ocasião.',
    ctaText: 'Saiba Mais',
    landingPageUrl: 'https://gama.com/blog/looks',
    status: 'active',
    startDate: '2026-03-28',
    daysActive: 3,
    score: 9,
    isWinner: false,
    isNew: true,
  },
  {
    id: 'ad3',
    externalId: 'ext_3',
    platform: 'meta',
    competitorId: '2',
    competitorName: 'Beta Store',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=400&h=500',
    headline: 'Frete Grátis para todo Brasil',
    text: 'Somente este final de semana, compre qualquer item e não pague frete.',
    ctaText: 'Aproveitar Agora',
    landingPageUrl: 'https://betastore.com.br/frete-gratis',
    status: 'active',
    startDate: '2026-03-30',
    daysActive: 1,
    score: 6,
    isWinner: false,
    isNew: true,
  },
];
